#!/usr/bin/env perl

use strict;
use warnings;

my $arg = shift;

require Path::Class::Dir;
my $outdir = Path::Class::Dir->new( 'output' );

if( !$arg ) {
    $outdir->rmtree;
    $outdir->mkpath;

    require File::Copy::Recursive;
    my $src = $outdir->parent->subdir( 'src' );
    File::Copy::Recursive::dircopy( "$src", "$outdir" );
}
elsif( $arg eq 'server' ) {
    require Plack::Loader;
    require Plack::App::Directory;
    my $app = Plack::App::Directory->new( { root => "$outdir" } )->to_app;
    print STDERR 'browse to http://localhost:1337/index.html', "\n";
    Plack::Loader->load( 'Standalone', port => 1337 )->run( $app );
}
